@startuml subject_area

!include styles.wsd

hide empty members
hide empty methods
left to right direction

' -----------------------------------------------

enum Роль {
    Клиент = 0
    Работник
    Админ
}

class Пользователь {
    ID: Число
    Логин: Строка
    Пароль: Строка
    Роль: Роль
    ---
    Дата_Регистрации: ДатаВремя
    ФИО: Строка
    Паспорт: Строка
}

Пользователь -r-> Роль

' -----------------------------------------------

enum СтатусТовара {
    В_залоге = 0
    Выкуплен
    На_продаже
    Продан
}

class Товар {
    ID: Число
    Название: Строка
    Дата_Приема: ДатаВремя
    Статус: СтатусТовара
    ---
    Работник: Число
    Комиссионные: Число
    Залогодатель: Число
    Стоимость_Залога: Число
    Дней_До_Выкупа: Число
    ---
    ID_Покупки: Число
} 

' Последняя стоимость 
' и есть стоимость продажи
class СтоимостьТовара {
    ID_Товара: Число
    Значение: Число
    Время: ДатаВремя
    Метка: Строка
}

Товар -d-> СтатусТовара
СтоимостьТовара -u-> Товар

' -----------------------------------------------

class Покупка {
    ID: Число
    ID_Клиента: Число
    Время: ДатаВремя
} 

Товар -l-> Покупка
Покупка --> Пользователь

@enduml