@startuml admin

!include styles.wsd

left to right direction

' nodes
' -----------------------------------------------

actor "Администратор" as admin

usecase "Войти В Систему" as sign_in
usecase "Добавить Пользователя" as add_user
usecase "Удалить Пользователя" as del_user
usecase "Просмотр Списка\nПользователей" as view_user_list
usecase "Поиск Пользователя" as find_user
usecase "Сортировать Пользователей\nПо Признаку" as sort_users

' edges
' -----------------------------------------------

admin -u-> sign_in
admin -u-> add_user
admin -u-> del_user
admin --> view_user_list
admin --> find_user
admin --> sort_users

@enduml