@startuml client

!include styles.wsd

' -----------------------------------------------

actor "Клиент" as client

left to right direction

client -r-> (Регистрация)
client -l-> (Войти В Систему)

client -u-> (Просмотр Списка\nТоваров)
client -u-> (Поиск Товара)
client -u-> (Добавить Товар\nВ Корзину)
client -u-> (Совершить Покупку)
client -d-> (Просмотр Истории Покупок)

client --> (Просмотр Истории\nСданных Вещей)
client --> (Сдать Вещь За Деньги)
client --> (Выкупить Вещь)

@enduml