@startuml employee

!include styles.wsd

' -----------------------------------------------

actor "Сотрудник" as employee

left to right direction

employee -r-> (Войти В Систему)
employee -u-> (Просмотр Списка\nТоваров)

' Оценить стоимость 
' принесенного в качестве залога товара
employee --> (Дать Деньги Под Залог)
employee -u-> (Редактировать Товар)

employee -u-> (Просмотр Всей\nИстории Покупок)

@enduml