@startuml user

!include styles.wsd

' -----------------------------------------------

actor "Пользователь" as user #Gray

actor "Администратор" as admin
actor "Сотрудник" as worker
actor "Клиент" as client

client -|> user
worker -|> client
admin -|> worker

@enduml