@startuml worker

!include styles.wsd

left to right direction

' -----------------------------------------------

actor "Сотрудник" as worker

worker -r-> (Войти В Систему)
worker -u-> (Просмотр Списка\nТоваров)

' Оценить стоимость 
' принесенного в качестве залога товара.
'   Добавить товар.
worker --> (Дать Деньги Под Залог)
worker --> (Редактировать Товар)

worker -u-> (Просмотр Всей\nИстории Покупок)

@enduml