@startuml subject_area

!include styles.wsd

hide empty members
hide empty methods

enum Роль {
    Клиент = 0
    Сотрудник
    Админ
}

class Пользователь {
    Идентификатор
    Логин
    Пароль
    Роль
    ---
    Имя
    Фамилия
    Дата Регистрации
}

class Клиент{} 
class Админ{} 
class Сотрудник{} 

Пользователь -l-> Роль
Клиент -u-|> Пользователь
Админ -u-|> Пользователь
Сотрудник -u-|> Пользователь

' -----------------------------------------------

class Товар {
    Идентификатор
    Название
    Количество
    ---
    Единица Измерения
    Стоимость Единицы
} 

class КупленныйТовар {
    Идентификатор
    ID Товара
    Количество    
}

class Покупка {
    ID Клиента
    Список IDs Товаров
    Дата

} 

Покупка --> Товар
Покупка --> Клиент

@enduml